spring.datasource.url=jdbc:h2:mem:librarydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.show-sql=true

mealdb.base-url=https://www.themealdb.com/api/json/v1/1

spoonacular.base-url=https://api.spoonacular.com
spoonacular.api-key=a7ce79241e044bfaaea1535470d17cff

cocktaildb.base-url=https://www.thecocktaildb.com/api/json/v1/1